sudo: required
services:
  - docker


before_install:
  - docker build -t ypratapa1988/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ypratapa1988/react-test npm test

after_success:
  - docker build -t ypratapa1988/multi-client ./client
  - docker build -t ypratapa1988/multi-nginx ./nginx
  - docker build -t ypratapa1988/multi-server ./server
  - docker build -t ypratapa1988/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ypratapa1988/multi-client
  - docker push ypratapa1988/multi-nginx
  - docker push ypratapa1988/multi-server
  - docker push ypratapa1988/multi-worker
